bot.py
This fixes the fun issue of !roll 100
=> Changed roll to be a single message as opposed to multiple

bot.py
I think it had to do with the weird printf needs. If you can merge it i can test it
=> Testing the roll

bot.py
=> Added check within roll that compliments the user if his rolls too

bot.py
=> Changed say back to what it should be

bot.py
I think this fixes it. Wanna look it over?
=> Fixing tts issues

bot.py
Also updated some formatting shtuff and error checking shtuff
=> Update roll command to allow RPG dice notation

bot.py
When pulling information from https://www.howmanyvaccinated.com/vaccine, i had (falsely) presumed that the first one i found would be the latest. I know now that the last one in the list is the most updated.
=> I Screwed Up

bot.py
See Title.
Will state uptime in this format:
```
Bot has been up 0 days, 0 hours, 0 minutes
Server has been up 1 day, 7 hours, 31 minutes
```
=> Adding uptime command that will display both server and bot uptime

bot.py
=> MaddAkeeno Wanted to add a Joe Mamma command

.gitignore, bot.py
It now does whatever maddie wants. Maddie is king.
Also we now have a small DB that we can add to for other things later.
=> Altered whoisjoe command

.gitignore, bot.py
Previously, upon attempting to add or subtract roles, a user would be greeted with a general message of "I've succeeded" or "I've failed"
Now it will check each role as it performs the appropriate function to it and will tell the user if the action succeeded or failed (because they had/didn't have the role or because the role doesn't exist)
=> Updates the Roles commands ['add', 'sub']

bot.py
Discord recently updated their API so that you have to enable certain settings before you'd be able to have a bot detect members joining and greet them. You have to enable this setting specifically in the bot's settings. View screenshot below:
=> Server Greeting and Intents

bot.py
To help mitigate a lot of the issues of global pings in discord. This will treat a role as special, giving it to everyone as they join, and the user can opt out of it if they so please.
=> Adds the Announcement role to new users

bot.py
Going to just merge this -- just doing a PR for the sake of history keeping. There's a silly little typo that makes the bot sound dumb
=> Fixes a stupid typo from 'keep update' to 'keep up to date'

bot.py, update.sh
Only allows 'Dallas' or 'Cody' roles to update the bot by running `!update`
this will call a script that will send keys to the tmux session that's running this bot.
=> Automatic deployment!

README.md, bot.py
I'm not letting the dream die
not yet, anyways. For the memes.
=> Add !prse command

bot.py
Reworks the vaccine command to allow for state data as well. State data comes from https://promotions.newegg.com/EC/covid19/vaccination/vaccina.json
This will allow a user to say "ca" or "california" and will normalize it so that "ca" will match with "CA"
=> Adds state data to vaccines

bot.py
We don't talk about this.
This should be used as an example as to why you should always thoroughly test your code.
=> Fixes issue where input would never match state

bot.py, cogs/fun.py, cogs/info.py, cogs/roles.py
Utilizing Cogs to reduce size of bot.py. I'm not sure if !whoisjoe and !joeis so please look at those but this works otherwise
=> Utilized Cogs

cogs/info.py
Should move sources. Technical debt!
=> Fixes issue where bot was unable to get newegg's data.

cogs/info.py, cogs/roles.py
=> Aliases for vaccines and myroles

bot.py, cogs/fun.py
=> Add yeet command

cogs/info.py
you'd like to check the joined time of.
Simple change, not sure if anyone is interested in a review, so i'll probably just merge.
=> Fixes #65 Updates joined to now allow arguments to check who

cogs/info.py
=> Fixes weird indentation issue with uptime command

cogs/info.py, requirements.txt
Adds a `!classes` command that lets users search for class times of a given subject and class number
=> Add Class Search Command, update requirements

cogs/roles.py, requirements.txt
I made probably a way to dumb to actually matter guessing system if you typed something wrong and hard coded allClass because I am a loser. Anyways this sanitizes via lower() and then if it is wrong takes a small, at max a size of 2, guess at what you were possibly trying to type
=> Possible answer to Issue #10

cogs/roles.py
I'm just doing this to make charon fully functional again. We should actually remedy this later.
=> Temporarily fixes the issue where capitalized names won't get resolved

cogs/info.py
I originally added this functionality to my own bot, which I've since added to the server. Two QR commands aren't necessary.
=> Remove QR command

cogs/fun.py, cogs/info.py
@Axanimander mentioned it so I did it. 
**Added !wiki command**
Gets the first paragraph of the page specified in the rest of the command.
**Example:**
=> Wikipedia command

cogs/fun.py
This should hopefully fix the bug that the ban command is experiencing
=> Bug fix of ban command

cogs/fun.py
!fact returns a random "fact" from this repo:
https://github.com/thomasdevine01/hackbot-functions/blob/main/fact.json
=> adds the !fact command

cogs/fun.py
simple command to return either trick or treat
=> added !trickortreat

cogs/info.py
Reduces confusion when people are looking for !serverroles
=> rename classes command
